# TASK-02

**Importing necessary libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**Load data into a Data the DataFrame**

In [2]:
df = pd.read_csv("dataset_2.csv")
df.head()

Id  Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6  \
0   1        6.1          4        4.4        4.2          0        5.5   
1   2        5.9          1        4.4        4.2          3        5.0   
2   3        5.7          4        4.3        4.2          2        5.2   
3   4        5.6          2        4.5        4.2          0        5.1   
4   5        6.0          5        4.4        4.2          1        5.6   

    Target  
0  Class_1  
1  Class_1  
2  Class_1  
3  Class_1  
4  Class_1

In [3]:
df

Id  Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6  \
0      1        6.1          4        4.4        4.2          0        5.5   
1      2        5.9          1        4.4        4.2          3        5.0   
2      3        5.7          4        4.3        4.2          2        5.2   
3      4        5.6          2        4.5        4.2          0        5.1   
4      5        6.0          5        4.4        4.2          1        5.6   
..   ...        ...        ...        ...        ...        ...        ...   
145  146        7.7          0        8.2        6.3          3        5.0   
146  147        7.3          4        8.0        5.9          0        4.5   
147  148        7.5          0        8.2        6.0          1        5.0   
148  149        7.2          1        8.4        6.3          0        5.4   
149  150        6.9          0        8.1        5.8          2        5.0   

      Target  
0    Class_1  
1    Class_1  
2    Class_1  
3    Class_1  
4    Class_1  
..       ...  
145  Class_3  
146  Class_3  
147  Class_3  
148  Class_3  
149  Class_3  

[150 rows x 8 columns]

In [4]:
df.describe()

Id   Feature_1   Feature_2   Feature_3   Feature_4   Feature_5  \
count  150.000000  150.000000  150.000000  150.000000  150.000000  150.000000   
mean    75.500000    6.843333    2.453333    6.758667    5.198667    2.426667   
std     43.445368    0.828066    1.759296    1.764420    0.763161    1.676312   
min      1.000000    5.300000    0.000000    4.000000    4.100000    0.000000   
25%     38.250000    6.100000    1.000000    4.600000    4.300000    1.000000   
50%     75.500000    6.800000    2.000000    7.350000    5.300000    2.000000   
75%    112.750000    7.400000    4.000000    8.100000    5.800000    4.000000   
max    150.000000    8.900000    5.000000    9.900000    6.500000    5.000000   

        Feature_6  
count  150.000000  
mean     5.054000  
std      0.433594  
min      4.000000  
25%      4.800000  
50%      5.000000  
75%      5.300000  
max      6.400000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Id         150 non-null    int64  
 1   Feature_1  150 non-null    float64
 2   Feature_2  150 non-null    int64  
 3   Feature_3  150 non-null    float64
 4   Feature_4  150 non-null    float64
 5   Feature_5  150 non-null    int64  
 6   Feature_6  150 non-null    float64
 7   Target     150 non-null    object 
dtypes: float64(4), int64(3), object(1)
memory usage: 9.5+ KB


**Finding out unique target values** 

In [6]:
df['Target'].unique()

array(['Class_1', 'Class_2', 'Class_3'], dtype=object)

**Converting the categorical "Target" variable to numeric by Label Encoding Method**

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(df['Target'])
label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
df.drop("Target", axis=1, inplace=True) 
df["Target"] = label
df

Id  Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6  \
0      1        6.1          4        4.4        4.2          0        5.5   
1      2        5.9          1        4.4        4.2          3        5.0   
2      3        5.7          4        4.3        4.2          2        5.2   
3      4        5.6          2        4.5        4.2          0        5.1   
4      5        6.0          5        4.4        4.2          1        5.6   
..   ...        ...        ...        ...        ...        ...        ...   
145  146        7.7          0        8.2        6.3          3        5.0   
146  147        7.3          4        8.0        5.9          0        4.5   
147  148        7.5          0        8.2        6.0          1        5.0   
148  149        7.2          1        8.4        6.3          0        5.4   
149  150        6.9          0        8.1        5.8          2        5.0   

     Target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 8 columns]

In [9]:
df['Target'].unique()

array([0, 1, 2])

## Performing EDA

**Here I have used sweetviz library for EDA that generates beautiful & high-density visualizations.**

In [10]:
import sweetviz as sv

my_report = sv.analyze(df)
my_report.show_html()

                                             |                                             | [  0%]   00:00 ->…

Report SWEETVIZ_REPORT.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.


In [11]:
df1=df.drop(['Feature_3','Id'], axis = 1)

In [12]:
df1

Feature_1  Feature_2  Feature_4  Feature_5  Feature_6  Target
0          6.1          4        4.2          0        5.5       0
1          5.9          1        4.2          3        5.0       0
2          5.7          4        4.2          2        5.2       0
3          5.6          2        4.2          0        5.1       0
4          6.0          5        4.2          1        5.6       0
..         ...        ...        ...        ...        ...     ...
145        7.7          0        6.3          3        5.0       2
146        7.3          4        5.9          0        4.5       2
147        7.5          0        6.0          1        5.0       2
148        7.2          1        6.3          0        5.4       2
149        6.9          0        5.8          2        5.0       2

[150 rows x 6 columns]

In [13]:
df1.shape

(150, 6)

**Checking for null values:**

In [14]:
df1.isna().sum()

Feature_1    0
Feature_2    0
Feature_4    0
Feature_5    0
Feature_6    0
Target       0
dtype: int64

**Creating two dataframes for dependent and independent columns each**

In [15]:
x=df1[['Feature_1','Feature_2','Feature_4','Feature_5','Feature_6']].values

In [16]:
x

array([[6.1, 4. , 4.2, 0. , 5.5],
       [5.9, 1. , 4.2, 3. , 5. ],
       [5.7, 4. , 4.2, 2. , 5.2],
       [5.6, 2. , 4.2, 0. , 5.1],
       [6. , 5. , 4.2, 1. , 5.6],
       [6.4, 2. , 4.4, 0. , 5.9],
       [5.6, 0. , 4.3, 5. , 5.4],
       [6. , 3. , 4.2, 2. , 5.4],
       [5.4, 4. , 4.2, 5. , 4.9],
       [5.9, 0. , 4.1, 5. , 5.1],
       [6.4, 1. , 4.2, 3. , 5.7],
       [5.8, 1. , 4.2, 3. , 5.4],
       [5.8, 0. , 4.1, 5. , 5. ],
       [5.3, 3. , 4.1, 3. , 5. ],
       [6.8, 2. , 4.2, 1. , 6. ],
       [6.7, 3. , 4.4, 4. , 6.4],
       [6.4, 1. , 4.4, 4. , 5.9],
       [6.1, 2. , 4.3, 5. , 5.5],
       [6.7, 4. , 4.3, 1. , 5.8],
       [6.1, 0. , 4.3, 2. , 5.8],
       [6.4, 5. , 4.2, 0. , 5.4],
       [6.1, 1. , 4.4, 3. , 5.7],
       [5.6, 1. , 4.2, 4. , 5.6],
       [6.1, 0. , 4.5, 1. , 5.3],
       [5.8, 2. , 4.2, 3. , 5.4],
       [6. , 5. , 4.2, 4. , 5. ],
       [6. , 0. , 4.4, 1. , 5.4],
       [6.2, 0. , 4.2, 1. , 5.5],
       [6.2, 0. , 4.2, 1. , 5.4],
       [5.7, 1

In [17]:
#dependent column
y=df1[['Target']]

In [18]:
y

Target
0         0
1         0
2         0
3         0
4         0
..      ...
145       2
146       2
147       2
148       2
149       2

[150 rows x 1 columns]

### Splitting training and test data


In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

### Feature Scaling

In [20]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.fit_transform(x_test)

In [21]:
x_train

array([[ 0.61303014,  0.31392496,  0.73603967, -0.18275003,  0.10850105],
       [-0.56776627,  1.43843227,  0.34808318,  1.59535841, -0.12400121],
       [-0.80392556, -1.37283601, -1.3330616 , -0.77545285,  1.03851009],
       [ 0.25879121,  0.31392496,  0.73603967, -0.77545285, -0.12400121],
       [ 0.61303014, -0.2483287 ,  1.25331499,  1.59535841, -0.58900572],
       [-0.80392556, -0.81058235,  0.21876435,  0.40995278, -0.82150798],
       [-0.21352735,  0.87617861, -1.20374277, -0.77545285,  1.73601687],
       [ 0.14071157,  0.87617861,  0.47740201, -1.36815566, -0.82150798],
       [ 0.02263193,  0.31392496,  0.34808318, -0.77545285, -0.12400121],
       [-0.09544771, -0.2483287 , -0.03987331,  1.59535841, -1.05401024],
       [ 1.0853487 ,  1.43843227,  1.12399616, -0.18275003, -0.12400121],
       [-1.39432376,  0.87617861, -1.3330616 , -0.18275003,  0.34100331],
       [ 1.20342834, -0.81058235,  1.38263382,  0.40995278,  0.10850105],
       [-1.04008484, -0.2483287 , -0.8

In [22]:
x_test

array([[ 0.14956537, -0.9100664 ,  1.91948971,  0.06608186, -0.58304897],
       [ 0.43000045,  0.30335547, -0.10102577, -0.59473674, -1.9460206 ],
       [-0.27108724, -0.9100664 , -1.25560605,  0.72690046,  2.59721815],
       [ 2.25282843,  0.9100664 ,  1.0535545 ,  0.06608186, -0.35588703],
       [-0.97217492,  0.30335547, -1.25560605, -0.59473674,  0.77992265],
       [ 0.85065306, -0.30335547,  2.06381224, -1.91637394,  0.55276071],
       [-0.97217492,  0.30335547, -1.11128352, -0.59473674,  1.00708459],
       [ 1.41152321, -1.51677734,  0.6205869 ,  0.06608186,  0.09843684],
       [ 1.55174074,  0.9100664 ,  0.47626436,  1.38771906, -0.58304897],
       [ 0.57021798, -0.9100664 ,  0.33194183,  0.72690046, -0.58304897],
       [ 0.57021798, -0.9100664 ,  0.47626436, -1.25555534, -1.03737285],
       [ 0.9908706 ,  0.9100664 ,  0.6205869 ,  0.72690046,  0.32559878],
       [ 0.57021798,  0.30335547,  0.18761929,  0.72690046, -0.58304897],
       [ 1.13108813,  0.9100664 ,  0.6

In [23]:
y_train

Target
137       2
84        1
27        0
127       2
132       2
..      ...
9         0
103       2
67        1
117       2
47        0

[120 rows x 1 columns]

In [24]:
y_test

Target
114       2
62        1
33        0
107       2
7         0
100       2
40        0
86        1
76        1
71        1
134       2
51        1
73        1
54        1
63        1
37        0
78        1
90        1
45        0
16        0
121       2
66        1
24        0
8         0
126       2
22        0
44        0
97        1
93        1
26        0

## Applying Different Algorithms

### Logistic Regression 

In [25]:
from sklearn import datasets, linear_model, metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
reg = linear_model.LogisticRegression()
reg.fit(x_train, y_train)
y_pred1 = reg.predict(x_test)

C:\Users\Anil\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


**Accuracy for Logistic Regression**

In [26]:
print("Logistic Regression model accuracy(in %):", metrics.accuracy_score(y_test, y_pred1)*100)

Logistic Regression model accuracy(in %): 83.33333333333334


**Confusion Matrix - Logistic Regression**

In [27]:
print("Confusion Matrix - Logistic Regression:\n",confusion_matrix(y_test, y_pred1))

Confusion Matrix - Logistic Regression:
 [[11  0  0]
 [ 0  8  5]
 [ 0  0  6]]


**Report**

In [28]:
print("Report : ", classification_report(y_test, y_pred1))

Report :                precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.62      0.76        13
           2       0.55      1.00      0.71         6

    accuracy                           0.83        30
   macro avg       0.85      0.87      0.82        30
weighted avg       0.91      0.83      0.84        30



###  Decision Tree Algorithm

In [29]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report


def train_using_gini(x_train, x_test, y_train):
    clf_gini = DecisionTreeClassifier(criterion = "gini",
            random_state = 100,max_depth=3, min_samples_leaf=5)
 
    clf_gini.fit(x_train, y_train)
    return clf_gini
      
def tarin_using_entropy(x_train, x_test, y_train):
    clf_entropy = DecisionTreeClassifier(
            criterion = "entropy", random_state = 100,
            max_depth = 3, min_samples_leaf = 5)
  
    clf_entropy.fit(x_train, y_train)
    return clf_entropy
  

def prediction(x_test, clf_object):
    y_pred2 = clf_object.predict(x_test)
    print("Predicted values:\n")
    print(y_pred2)
    return y_pred2
      

def cal_accuracy(y_test, y_pred2):    
    print("Confusion Matrix: \n",confusion_matrix(y_test, y_pred2))
    print ("Accuracy : ", accuracy_score(y_test,y_pred2)*100)
    print("Report:\n ", classification_report(y_test, y_pred2))

def main():
    
    clf_gini = train_using_gini(x_train, x_test, y_train)
    clf_entropy = tarin_using_entropy(x_train, x_test, y_train)
    print("Results Using Gini Index:\n")
    print("*****************************************************")
    y_pred_gini = prediction(x_test, clf_gini)
    cal_accuracy(y_test, y_pred_gini)
    print("Results Using Entropy:\n")
    print("*****************************************************")

    y_pred_entropy = prediction(x_test, clf_entropy)
    cal_accuracy(y_test, y_pred_entropy)
      
if __name__=="__main__":
    main()

Results Using Gini Index:

*****************************************************
Predicted values:

[2 1 0 2 0 2 0 1 1 1 1 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
Confusion Matrix: 
 [[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
Accuracy :  96.66666666666667
Report:
                precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.93      1.00      0.96        13
           2       1.00      0.83      0.91         6

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30

Results Using Entropy:

*****************************************************
Predicted values:

[2 1 0 2 0 2 0 1 1 1 1 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
Confusion Matrix: 
 [[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
Accuracy :  96.66666666666667
Report:
                precision    recall  f1-score   support

           0       1.00      1.00      1.00      

### Naive Bayes 

In [30]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)
y_pred3 = gnb.predict(x_test)


C:\Users\Anil\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


**Accuracy for Naive Bayes**

In [31]:
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred3)*100)

Gaussian Naive Bayes model accuracy(in %): 80.0


### Support Vector Machine

In [32]:
from sklearn.svm import SVC 
from sklearn.metrics import accuracy_score, confusion_matrix
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(x_train, y_train)

C:\Users\Anil\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVC(kernel='linear', random_state=0)

In [33]:
y_pred4= classifier.predict(x_test)  
y_pred4

array([2, 1, 0, 2, 0, 2, 0, 2, 2, 1, 2, 1, 1, 2, 1, 0, 2, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

**Accuracy for SVM**

In [34]:
print(classifier.score(x_train, y_train))
print(classifier.score(x_test, y_test))

0.9583333333333334
0.8666666666666667


**Confusion Matrix - SVM:**

In [35]:
from sklearn.metrics import confusion_matrix  
cm_svm= confusion_matrix(y_test, y_pred4)
print("Confusion Matrix - SVM\n",cm_svm)

Confusion Matrix - SVM
 [[11  0  0]
 [ 0  9  4]
 [ 0  0  6]]


### XGBoost Algorithm

In [36]:
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
classifier = XGBClassifier()
classifier.fit(x_train, y_train)
y_pred5 = classifier.predict(x_test)

C:\Users\Anil\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


**Accuracy of XGBoost**

In [37]:
print("Accuracy of XG-Boost:\n",accuracy_score(y_test, y_pred5)*100)

Accuracy of XG-Boost:
 90.0


**Confusion Matrix - XGBoost**

In [38]:
cm_xg = confusion_matrix(y_test, y_pred5)
print("Confusion Matrix - XGBoost:\n",cm_xg)

Confusion Matrix - XGBoost:
 [[11  0  0]
 [ 0 10  3]
 [ 0  0  6]]


**we want to test few other algorithms for regression to see if we can get even better score. We will use GridSearchCV for this purpose**

In [39]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import ShuffleSplit

def find_best_model_using_gridsearchcv(x,y):
    algos = {
        'linear_regression' : {
            'model': LinearRegression(),
            'params': {
                'normalize': [True, False]
            }
        },
        
        'decision_tree': {
            'model': DecisionTreeRegressor(),
            'params': {
                'criterion' : ['mse','friedman_mse'],
                'splitter': ['best','random']
            }
        }
    }
    scores = []
    cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
    for algo_name, config in algos.items():
        gs =  GridSearchCV(config['model'], config['params'], cv=cv, return_train_score=False)
        gs.fit(x,y)
        scores.append({
            'model': algo_name,
            'best_score': gs.best_score_,
            'best_params': gs.best_params_
        })

    return pd.DataFrame(scores,columns=['model','best_score','best_params'])

find_best_model_using_gridsearchcv(x,y)

model  best_score                                 best_params
0  linear_regression    0.914862                        {'normalize': False}
1      decision_tree    0.875841  {'criterion': 'mse', 'splitter': 'random'}